name = "sub"
main = "src/index.js"
compatibility_date = "2026-06-27"

[compatibility_flags]

# Очень важно, чтобы НЕ БЫЛО строчки вроде format = "service-worker"
# Если используется [build], убедиться, что тип сборки указан как ES модули.
